"""Strongly typed, non-runtime contracts for three-role collaboration."""

from .contracts import (
    ARTIFACT_TYPES,
    PRODUCER_ROLES,
    AgentTask,
    ArtifactEnvelope,
    ArtDirection,
    EntityBindingPlan,
    GameDesignBrief,
    GameProjectState,
    GameplayLogicPlan,
    LevelPlan,
    NonExecutableArtifactError,
    SceneCompositionPlan,
    ValidationResult,
    assert_executable,
    validate_artifact_payload,
)
from .project_state import (
    InvalidProjectStateTransitionError,
    ProjectAlreadyExistsError,
    ProjectNotFoundError,
    ProjectPatchConflictError,
    ProjectStatePatch,
    ProjectStateStore,
    ProjectStateTransition,
    ProjectVersionConflictError,
)

__all__ = [
    "ARTIFACT_TYPES",
    "PRODUCER_ROLES",
    "AgentTask",
    "ArtifactEnvelope",
    "ArtDirection",
    "EntityBindingPlan",
    "GameDesignBrief",
    "GameProjectState",
    "GameplayLogicPlan",
    "LevelPlan",
    "NonExecutableArtifactError",
    "SceneCompositionPlan",
    "ValidationResult",
    "assert_executable",
    "validate_artifact_payload",
    "InvalidProjectStateTransitionError",
    "ProjectAlreadyExistsError",
    "ProjectNotFoundError",
    "ProjectPatchConflictError",
    "ProjectStatePatch",
    "ProjectStateStore",
    "ProjectStateTransition",
    "ProjectVersionConflictError",
]
